# Welcome to Jekyll!
#

# Site settings
title: Insper`s Finance and Macro Unit 
description: |
  The web page of Finance and Macroeconomics 
  study unit at Insper
owner: CeFiM
first_published: 2024
email: cefim@insper.edu.br
baseurl: ""
# url: "http://localhost:4000"
permalink: pretty
collections:
  publications:
